services:
  eureka-server:
    build: eureka-server
    mem_limit: 999m
    ports:
      - "8761:8761"
    networks:
      - "donelt-network"
  api-gateway:
    build: api-gateway
    mem_limit: 999m
    ports:
      - "444:444"
    networks:
      - "donelt-network"
    depends_on:
      - eureka-server
  notification-server:
    build: notification-service
    mem_limit: 999m
    ports:
      - "9001:9001"
    networks:
      - "donelt-network"
    environment:
      - JWT_KEY=${JWT_KEY}
      - JWT_USER=${JWT_USER}
  task-server:
    build: task-service
    mem_limit: 999m
    ports:
      - "9000:9000"
    networks:
      - "donelt-network"
    environment:
      - JWT_KEY=${JWT_KEY}
      - JWT_USER=${JWT_USER}
  user-server:
    build: user-service
    mem_limit: 999m
    ports:
      - "9002:9002"
    networks:
      - "donelt-network"
    environment:
      - JWT_KEY=${JWT_KEY}
      - JWT_USER=${JWT_USER}
networks:
  donelt-network:
